---
current_directory: images/linux/amazon-2023
image_name: Amazon-Linux-2023-Server-Base-Image
ami_description: Amazon Linux 2023 Server Base Image
build_host_instance_type: t2.micro
parent_image: amazon-linux-2023-x86/x.x.x
image_builder_platform: Linux
image_pipeline_scheduler: cron(30 22 ? * tue#2 *)  # Run on the second Tuesday of every month at 10:30 PM (UTC)
