---
name: BuildComponent
description: Build Component
schemaVersion: 1.0
phases:
  - name: build
    steps:
      - name: Initialize-All-Volumes
        action: ExecutePowerShell
        onFailure: Abort
        inputs:
          commands:
            - |
              Get-Disk |
                Where-Object PartitionStyle -Eq "RAW" |
                Initialize-Disk -PassThru -PartitionStyle MBR |
                New-Partition -AssignDriveLetter -UseMaximumSize |
                Format-Volume -FileSystem NTFS
