---
name: Build AMI for Windows Server 2025
on:
  workflow_dispatch:

# required for GitHub OIDC - https://github.com/aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Deploy Resources
    runs-on: ubuntu-latest
    steps:
      - name: Allow Workflow access to repo
        uses: actions/checkout@v4

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActions

      - name: Retrieve credentials
        run: aws sts get-caller-identity

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Account Resources
        run: |
          cd sceptre
          sceptre launch -y images/windows/server-2025/infra/image-creation-stack.yaml
